site_name: The Human Experiment
site_description: A deep dive into the human condition and social dynamics.
site_author: Rez Khan
site_url: https://universalbookcompiler.com/30_The_Human_Experiment/
site_dir: ../site_build
docs_dir: docs
nav:
- index.md
- Introduction: introduction-a-people-without-a-story.md
- 'Part 1: The Anomalies':
  - part-1-the-anomalies.md
  - chapter-1-the-unsettling-data.md
  - chapter-2-stones-that-should-not-be.md
  - chapter-3-echoes-in-the-bone-and-blood.md
  - chapter-4-the-ghost-in-the-machine.md
- 'Part 2: The Investigation':
  - part-2-the-investigation.md
  - chapter-5-the-mythological-evidence.md
  - chapter-6-the-two-factions.md
  - chapter-7-the-consciousness-upgrade.md
  - chapter-8-the-great-trauma.md
  - chapter-9-the-war-in-the-blood.md
- 'Part 3: The Human Condition':
  - part-3-the-human-condition.md
  - chapter-10-the-inner-battlefield.md
  - chapter-11-the-engine-vs-the-family.md
  - chapter-12-the-war-on-magic.md
  - chapter-13-the-modern-manifestation.md
- 'Part 4: The Liberation':
  - part-4-the-liberation.md
  - chapter-14-the-choice-point.md
  - chapter-15-the-liberation-practices.md
- Conclusion: conclusion-the-experiment-is-over.md
- Downloads: downloads/index.md
theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  - content.tabs.link
  font:
    text: Inter
    code: Fira Code
plugins:
- search
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.details
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- codehilite
- toc
- tables
- footnotes
- attr_list
- md_in_html
extra_css:
- stylesheets/custom.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DoctorKhan/Universal-Book-Compiler
copyright: Copyright &copy; 2025 Rez Khan
